### ISSUE TITLE
Reconnect Issue?

### ISSUE THREAD

**Issue by akeilox** [tobiasisenberg/OxiVis#1]
This may be related to esp32 wroom module i am using, when simulating an overnight study and wake up for a bathroom break (leave the esp32 vicinity) and upon returning back it didnt seem to re-connect the BLE. I thought it might be a one off thing so i restarted the module and tried again and i can reproduce it. Its as if the module frozen.
I flashed with these settings (for reference, as it didnt flash with default 1,2/1.5 partition scheme);
![image](https://user-images.githubusercontent.com/4035501/88460431-c613e980-cece-11ea-8073-f94b6cdc81c3.png)

This is the serial log;
`Posting data to MQTT from buffer 0
Posting data to MQTT took 274ms.
Result of data message was: 1

Posting data to MQTT from buffer 1
Posting data to MQTT took 44ms.
Result of data message was: 1

Posting data to MQTT from buffer 2
Posting data to MQTT took 22ms.
Result of data message was: 1
BLE Disconnected

BLE Advertised Device found: Name: , Address: 7c:49:eb:0a:dd:86, manufacturer data: 8f030a10e4020084dd0aeb497c81
Address: 7c:49:eb:0a:dd:86
Device does not have Service UUID

BLE Advertised Device found: Name: , Address: 2d:b7:24:0d:1a:47, manufacturer data: 060001092002de3709bd3b18f2b7dd2f92151e4593e149d2e5a71f3e4e
Address: 2d:b7:24:0d:1a:47
Device does not have Service UUID

BLE Advertised Device found: Name: , Address: 00:c3:f4:17:b6:1f, manufacturer data: 7500420401806000c3f417b61f02c3f417b61e01000000000000
Address: 00:c3:f4:17:b6:1f
Device does not have Service UUID

BLE Advertised Device found: Name: , Address: 76:13:55:89:75:fa, manufacturer data: 4c001006131e87fa8dc3, txPower: 12
Address: 76:13:55:89:75:fa
Device does not have Service UUID

BLE Advertised Device found: Name: PR BT 34C0, Address: 00:1f:ff:86:af:7f, manufacturer data: 000000000000
Address: 00:1f:ff:86:af:7f
Device does not have Service UUID

BLE Advertised Device found: Name: , Address: 2d:b7:24:0d:1a:47, manufacturer data: 060001092002de3709bd3b18f2b7dd2f92151e4593e149d2e5a71f3e4e
Address: 2d:b7:24:0d:1a:47
Device does not have Service UUID

BLE Advertised Device found: Name: , Address: 76:13:55:89:75:fa, manufacturer data: 4c001006131e87fa8dc3, txPower: 12
Address: 76:13:55:89:75:fa
Device does not have Service UUID

BLE Advertised Device found: Name: , Address: 00:c3:f4:17:b6:1f, manufacturer data: 7500420401806000c3f417b61f02c3f417b61e01000000000000
Address: 00:c3:f4:17:b6:1f
Device does not have Service UUID

BLE Advertised Device found: Name: , Address: 7c:49:eb:0a:dd:86, manufacturer data: 8f030a10e4020084dd0aeb497c81
Address: 7c:49:eb:0a:dd:86
Device does not have Service UUID

BLE Advertised Device found: Name: PR BT 34C0, Address: 00:1f:ff:86:af:7f, manufacturer data: 000000000000
Address: 00:1f:ff:86:af:7f
Device does not have Service UUID

BLE Advertised Device found: Name: BerryMed
Address: 00:a0:50:39:92:23
Device does not have Service UUID
Found a device that contains the service we are looking for.
Forming a connection to 00:a0:50:39:92:23
BLE Disconnected
`

**Comment by tobiasisenberg** [comment]
Hi @akeilox ,

That the flashing with the normal partitioning scheme does not work is known; in the readme I recommended to use the `Minimal SPIFFS` partitioning scheme, but the `Huge APP` scheme will do just fine as well.

The disconnect issue is one thing I also worked on. For me the device reconnects. What would be interesting for me to know is what happens after your log ended, does it just stop there or are there re-connect attempts (or is it frozen as you say)? I made quite some effort to get the BLE to reconnect as well when you move out of range, so maybe you could post a longer log? If possible, please use code blocks to post you log files, this is much easier to read.

**Comment by tobiasisenberg** [comment]
Just as a follow-up, here is a trace from the same experiment with my device:
```
Starting Arduino BLE Client application...
 - Device initialized
 - Created client
 - Client callbacks set

BLE Advertised Device found: Name: , Address: 6d:24:41:27:58:01, manufacturer data: 0600010920027e1382d1bfaccbe31b325851e7b5f979d5276e8af51745
Address: 6d:24:41:27:58:01
Device does not have Service UUID
Enabling scanning.

BLE Advertised Device found: Name: , Address: 6d:24:41:27:58:01, manufacturer data: 0600010920027e1382d1bfaccbe31b325851e7b5f979d5276e8af51745
Address: 6d:24:41:27:58:01
Device does not have Service UUID

BLE Advertised Device found: Name: BerryMed
Address: 00:a0:50:db:83:94
Device does not have Service UUID
Found a device that contains the service we are looking for.
Forming a connection to 00:a0:50:db:83:94
BLE Connected
 - Connected to server
 - Found our service
 - Found our characteristic 49535343-1e4d-4bd9-ba61-23c647249616
 - Our characteristic cannot be read.
 - Our characteristic can notify us, registering notification callback.
 - Our characteristic cannot indicate.
We are now connected to the BLE Server.
Starting new trace, publishing new Oximeter connection timestamp to MQTT.

Posting data to MQTT from buffer 0
Posting data to MQTT took 7ms.
Result of data message was: 1

Posting data to MQTT from buffer 1
Posting data to MQTT took 7ms.
Result of data message was: 1

Posting data to MQTT from buffer 2
Posting data to MQTT took 11ms.
Result of data message was: 1

Posting data to MQTT from buffer 3
Posting data to MQTT took 72ms.
Result of data message was: 1
BLE Disconnected

BLE Advertised Device found: Name: , Address: 6d:24:41:27:58:01, manufacturer data: 0600010920027e1382d1bfaccbe31b325851e7b5f979d5276e8af51745
Address: 6d:24:41:27:58:01
Device does not have Service UUID

BLE Advertised Device found: Name: BerryMed
Address: 00:a0:50:db:83:94
Device does not have Service UUID
Found a device that contains the service we are looking for.
Forming a connection to 00:a0:50:db:83:94
BLE Connected
 - Connected to server
 - Found our service
 - Found our characteristic 49535343-1e4d-4bd9-ba61-23c647249616
 - Our characteristic cannot be read.
 - Our characteristic can notify us, registering notification callback.
 - Our characteristic cannot indicate.
We are now connected to the BLE Server.
Starting new trace, publishing new Oximeter connection timestamp to MQTT.
BLE Disconnected

BLE Advertised Device found: Name: BerryMed
Address: 00:a0:50:db:83:94
Device does not have Service UUID
Found a device that contains the service we are looking for.
Forming a connection to 00:a0:50:db:83:94
BLE Connected
 - Connected to server
 - Found our service
 - Found our characteristic 49535343-1e4d-4bd9-ba61-23c647249616
 - Our characteristic cannot be read.
 - Our characteristic can notify us, registering notification callback.
 - Our characteristic cannot indicate.
We are now connected to the BLE Server.
Starting new trace, publishing new Oximeter connection timestamp to MQTT.
Incorrect packet length!!!

Posting data to MQTT from buffer 0
Posting data to MQTT took 29ms.
Result of data message was: 1

Posting data to MQTT from buffer 1
Posting data to MQTT took 12ms.
Result of data message was: 1
```
As you can see, the device disconnected (when I walked away), then tried to reconnect, failed, and reconnected again, this time successfully.

**Comment by tobiasisenberg** [comment]
@akeilox ,

I looked at the code again. Please check, in the `connectToServer()` function, the line
```
  boolean connectionSuccessful = pClient->connect(myDevice);
```
Apparently your device does not go past this line (otherwise we would see more print-outs and it would not freeze). Could you try to replace this line with the following line:
```
  boolean connectionSuccessful = pClient->connect(myDevice->getAddress());
```
and then try again to see f the problem persists? This is a part I used from the example BLE sketch, so this is only a hunch. Let me know what you find. If you get further output beyond the failure to re-connect to BLE, as I noted before, that would also be helpful. Thanks!

**Comment by akeilox** [comment]
Hi @tobiasisenberg thank you for the feedback. I changed connecToServer() function as you suggested and the behaviour did not change.
I have now ordered a new ESP32 wroom unit as I suspect its something to do with the unit i have.
Will keep you posted.
