### ISSUE TITLE
Adding support for Contec CMS50D-BT

### ISSUE THREAD

**Issue by jokubasver** [tobiasisenberg/OxiVis#2]
I am trying to adapt your code to support this Contec CMS50D-BT oximeter. But I am having issues. 

You can see the changelog here: https://github.com/jokubasver/OxiVis/commit/35c159698ef362c76972c0efaa8cdb7894d65c26

Thanks to Android Bluetooth logging and Wireshark, I was able to read data from it - the main thing it needed was to send `0x9b011c` to `0000ff01-0000-1000-8000-00805f9b34fb` characteristics UUID for the other characteristics UUID (`0000ff02-0000-1000-8000-00805f9b34fb`) to spit out data. 

`0x9b011c` needs to be sent often, as otherwise the meter only sends data for less than a minute and then stops, so I had to move the `writeValue` command into the `void loop`. 

Also, `pRemoteCharacteristicOximeter->getDescriptor(BLEUUID((uint16_t)0x2902))->writeValue((uint8_t*)notificationOn, 2, true);` didn't work in my case, so I did it a bit differently, but I am not sure if I did it properly.

One issue I was having is an "Incorrect packet length" error on ESP serial. 
Not sure if this is a correct fix, but since the hex length in my case is 8:
> Notify callback for characteristic 0000ff02-0000-1000-8000-00805f9b34fb of data length 8
> data (HEX): EB 1 4 40 63 7F 0 12 

I changed `int packetCount` to equel `length / 2;`.

With this change, the error goes away and I am able to see data via serial print commands, but it takes around 10 minutes for the data to be saved to csv, which seems too long. The data also has some garbage in the csv file too, so I'm not sure what's going on. Maybe there is an issue with the buffer while using this Contec meter.

I'm attaching an example csv file.
[oximeter-20211008-203743-12079.csv](https://github.com/tobiasisenberg/OxiVis/files/7313555/oximeter-20211008-203743-12079.csv)

Some data from MQTT Explorer:
> data = ;�Ec����&LzEc����&R�Dc����&^gBc����&bOBc����&fBAc����&jAc����&n	Ac����&u�@c����&~z?c����&�x@c����&�`@c����&�Q@c����&��@c����&�dAc����&�4Ac����&�Ac����&�Bb����&��Bb����&��Bb����&��Cb����&��Eb����&��Fb����&�GFb����&��Gc����&��Hc����&�Ic����&��Ic����&Hc����&F�Gc����&MzGc����&URGc����&aeGc����&eMGc����&qGc����&x�Gc����&��Gc����&��Fc����&�.Fc����&�kFc����&��Fc����&�Fc����&�ZFc����&�yFc����&��Fc����&�Fc����&�jEc����&�FCc����&�zCc����&	�Cc����&ECc����&{Dc����&KDc����&)gDc����&-�Dc����&REc����&g�Ec����&k�Ec����&o�Ec����&s�Ec����&w�Ec����&{pEc����&YEc����&�Ec����&�[Ec����&�8Ec����&��Dc����&��Dc����&�nDc����&Dc����&��Dc����&��Dc����&��Dc����&լEc����&ٔEc����&�NEc����&�Ec����&�PEc����&� Ec����&�Ec����&	�Ec����&$1Bc����&,Ac����&3�@c����&<@c����&Lw@c����&W�@c����&]D@c����&f�@c����&j�@c����&n�@c����&s@c����&z�@c����&5@c����&�>@c����&�%@c����&�D@c����&��@c����&��?c����&��?c����&��?c����&�~@c����&�f@c����&�NAc����&�7Ac����&��Ac����&�EBc����&�Cc����&�Dc����&�JEc����&�Ec����&��Ec����&Ec����&rEc����&ZEc����&�Ec����&wEc����&^Ec����&#FEc����&'/Ec����&.�Fc����&6�Ic����&:�Jc����&>� Nc����&B�!Oc����&F�#Qc����&R'$Rc����&Y�$Rc����&a�$Rc����&e�$Rc����&i�$Rc����&m$Rc����&yD$Rc����&}$Rc����&�l$Rc����&��$Rc����&�p$Rc����&��$Rc����&�v#Qc����&�{#Qc����&�L!Oc����&�Lc����&��Jc����&ǼIc����&�wGc����&�\Gc����&�,Fc����&��Fc����&�HFc����&��Fc����&�Gc����&�4Gc����&Fc����&:Fc����&@Ec����&tEc����&*,Fc����&1�Fc����&9hGc����&A�Gc����&L�Fc����&RFc����&Y
Fc����&\�Fc����&`�Fc����&d�Fc����&h�Fb����&l�Fc����&teFc����&xMFc����&|5Ec����&�Ec����&�Ec����&��Ec����&��Ec����&��Ec����&�]Dc����&�EDc����&�.Dc����&�Ec����&��Ec����&��Ec����&�2Ec����&�Ec����&��Ec����&�7Ec����&ҊEc����&רDc����&�*Ec����&��Ec����&��Ec����&��Ec����&��Ec����&��Ec����&Ec����&uEc����&!Ec����&(�Ec����&,�Ec����&0�Ec����&4�Fc����&8~Gc����&@OHb����&D8Hb����&HHb����&L�Gb����&W�Gb����&]BGb����&cwFb����&g_Ec����&kGEc����&o/Dc����&sDc����&wEc����&��Ec����&�Ec����&��Ec����&�8Ec����&��Fc����&��Fc����&�sGc����&�[Hc����&�+Ic����&��Hc����&��Jc����&ńJc����&�TJc����&�Jc����&�Ic����&�~Ic����&�dIc����&��Ib����&�Hb����&jHb����&PGb����&9Fb����&�Fb����&�Fb����&'�Gc����&/`Gc����&71Gc����&;Gc����&B�Fc����&G6Fc����&OGc����&R�Fc����&W�Fc����&^�Ec����&b�Ec����&fuEc����&nEEc����&�UFc����&�tFc����&��Hb����&��Ib����&��Ib����&��Ib����&ȁIb����&�uIb����&�"Ib����&�6Ic����&��Jc����&�Jc����&�zJc����&�cIc����&�JIc����&�2Ic����&Gc����&
�Fc����&AEc����&�Cc����& 
Bc����&&DBc�?��$�&*�Bc����&.vAc����&2^Ac����&6FAc����&:/Ac����&>Ac����&A�Ac����&E�Bc����&I�Bc����&M�Bc����&RBc����&YoBc����&]WCc����&a?Cc����&e'Dc����&iDc����&l�Dc����&p�Ec����&t�Dc����&x�Cc����&|�Cc����&�Bc����&�sBc����&�OBc����&��Bc����&��Bc����&��Bc����&�<Cc����&��Cc����&��Cc����&��Cc����&��Cc����&��Cc����&�dCc����&�KCc����&�5Cc����&�Cc����&�Bc����&��Bc����&צAc����&ޤ@c����&�@c����&�}@c����&�x?c����&�H?c����&	?c����&	
?c����&	�@c����&	sAc����&	!pBc����&	%�Cc����&	1Dc����&	8�Dc����&	=,Dc����&	D�Cc����&	L�Cc����&	P�Cc����&	T�Cc����&	X�Cc����&	]?Cc����&	d=Cc����&	h%Dc����&	l
Dc����&	o�Dc����&	w�Dc����&	{�Eb����&	�Fb����&	�}Fb����&	�eFb����&	�MFb����&	��Fb����&	�Fc����&	��Ec����&	�Ec����&	��Dc����&	��Dc����&	��Dc����&	�aDc����&	�IDc����&	�gDc����&	��Dc����&	�BDc����&	�Dc����&	��Dc����&
�Cc����&
�Cc����&
�Cc����&
�Cc����&
�Bc����&
�Bc����&
 �Bc����&
%�Bc����&
4Cc����&
8ZCc����&
?�Cc����&
OhDc����&
SNDc����&
W�Dc����&
_Ec����&
cREc����&
hsEb����&
r�Ec����&
> bpm = 63
> spo2 = 99

I am also not quite sure yet where the PPG data is. It could be the last byte of that hex stream, but I also found that sending `0x9b001b` gives a another stream of data, which might be the PPG stream.

Any help would be greatly appreciated.

**Comment by jokubasver** [comment]
Git didn't commit a few changes to my fork, so here they are: https://github.com/jokubasver/OxiVis/commit/cf6bcb0f298ddf9399ea905089665737574084d6

**Comment by jokubasver** [comment]
I think I found all the values.

I'll repeat myself to be clear:
Writing `0x9b011c` to characteristics UUID `0000ff01-0000-1000-8000-00805f9b34fb` turns on data streaming/notifications.
Data is streamed on `0000ff02-0000-1000-8000-00805f9b34fb` characteristics UUID.

There are two separate hex strings:
- One is for SpO2 and heart rate. It's length is 8 and the hex string starts with 0xEB01
- The other - PPG and bar graph. It's length is 6 and the hex string starts with 0XEB00

> ---8 byte stream - SpO2, BPM---
> Hex: eb 01 04 53 63 7f 00 25 
> Dec: 235 1 4 83 99 127 0 37 
> -
> 1st byte - 235 (Constant)
> 2nd byte - 1 (Identifier that the byte stream is for SpO2 and BPM)
> 3rd byte - 4/6 (Probably a finger detector - 04 when no finger, 06 when finger is in device)
> 4th byte - 83 (BPM)
> 5th byte - 99 (SpO2)
> 6th byte - 127 (Doesn't change)
> 7th byte - 0 (Doesn't change)
> 8th byte - 37 (Unknown, seems to be BPM but values are shifted down by 46 units)

![8 byte stream](https://user-images.githubusercontent.com/4341386/136657505-a9c785f6-90cc-40fe-a8ce-efb886782396.PNG)

> ---6 byte stream (PPG, bar graph)---
> Hex: eb 00 03 48 09 3f
> Dec: 235 0 3 72 9 63 
> Hex: eb 00 43 3c 07 71
> Dec: 235 0 67 60 7 113
> -
> 1st byte - 235 (Constant)
> 2nd byte - 0 (Identifier that the byte stream is for PPG)
> 3rd byte - PPG peak detector? (When PPG is at the highest peak, this 3rd byte goes high)
> 4th byte - PPG
> 5th byte - Bar graph? (Basically looks like a low resolution PPG when graphed to a line chart)
> 6th byte - PPG, but with exaggerated peaks and different scale

![6 byte stream1](https://user-images.githubusercontent.com/4341386/136657553-ad5c3546-2992-4f3c-8914-712f9a24850b.PNG)
![6 byte stream2](https://user-images.githubusercontent.com/4341386/136657554-d5474470-54dc-4356-9d98-7c69d7937912.PNG)

Graphs were made with extracted data from Android Bluetooth logs and Wireshark.

Some data points are missing from my own data extraction to Google Sheets, as sometimes the hex string arrives two or three times in a row (for example instead of` eb000348093f` it's sometimes `eb000348093feb000348093f`)

Now I need to see what data is streamed when sending `0x9b001b `instead of `0x9b011c`

**Comment by tobiasisenberg** [comment]
Hi @jokubasver! Great that you try to make this work also for another device. I vaguely remember that there was also a low-res PPG value in my data. But since I do not have this specific oximeter I am afraid I cannot help much, but if you have a pull request that makes it possible to run the code on either device I would love to see it. Great work!

**Comment by tobiasisenberg** [comment]
Closing issue.
